class Kalip {
  static String fiilMadi;
  static String fiilMudari;
  static String yMasdar;
  static String ismiFail;
  static String ismiMeful;
  static String cahdiMutlak;
  static String cahdiMustagrak;
  static String nefiHal;
  static String nefiIstikbal;
  static String tekitNefiIstikbal;
  static String emriGaib;
  static String nehiGaib;
  static String emriHadir;
  static String nehiHadir;
  static String ismiMekan;
  static String ismiAlet;
  static String merreMastar;
  static String neviMastar;
  static String ismiTasgir;
  static String ismiMensub;
  static String mubalagaIsmiFail;
  static String ismiTafdil;
  static String taaccub1;
  static String taaccub2;
}
