import 'kaliplar.dart';

enum Kisim {
  SAHIH,
  MISAL,
  ECVEF,
  NAKIS,
  LEFIFMKRN,
  LEFIFMFRK,
  MUDAAF,
  MEHMUZF,
  MEHMUZA,
  MEHMUZL,
  MISALMUDAAF,
  MEHMUZFMUDAAF,
  MEHMUZFNAKIS,
  MEHMUZANAKIS,
  MEHMUZALEFIFMFRK,
}

class Veri {
  static Kisim durum = Kisim.SAHIH;

  static final List<String> harf = [
    "ا",
    "ب",
    "ت",
    "ث",
    "ج",
    "ح",
    "خ",
    "د",
    "ذ",
    "ر",
    "ز",
    "س",
    "ش",
    "ص",
    "ض",
    "ط",
    "ظ",
    "ع",
    "غ",
    "ف",
    "ق",
    "ك",
    "ل",
    "م",
    "ن",
    "و",
    "ه",
    "ي",
    "ئ",
    "ء",
    "ؤ",
    "ى",
    "ة",
    "أ",
  ];

  static final List<String> hareke = [
    "َ",
    "ِ",
    "ُ",
    "ً",
    "ٍ",
    "ٌ",
    "ْ",
    "إ",
    "أ",
    "آ",
    "ّ",
  ];

  static final List<String> bab = [
    "اَلْبَابُ الْاَوَّلُ",
    "اَلْبَابُ الثَّانِي",
    "اَلْبَابُ الثَّالِثُ",
    "اَلْبَابُ الرَّابِعُ",
    "اَلْبَابُ الْخَامِسُ",
    "اَلْبَابُ السّادِسُ",
  ];

  static final List<String> masdar = [
    "فَعْلًا",
    "فِعَالَةً",
    "فِعَالًا",
    "فَعَلَانًا",
    "فُعَالًا",
    "فُعْلَةً",
    "فَعِيلًا",
    "فُعُولَةً",
    "فَعَالَةً",
    "فَعَلًا",
    "فُعُولًا",
    "فِعْلًا",
    "فُعْلًا",
  ];

  static List yirmi4 = [
    Kalip.fiilMadi,
    "${Veri.harf[27]}${Kalip.fiilMudari}${Veri.hareke[2]}",
    Kalip.yMasdar,
    "${Kalip.ismiFail}${Veri.hareke[5]}",
    "${Kalip.ismiMeful}${Veri.hareke[5]}",
    "${Kalip.cahdiMutlak}${Veri.hareke[6]}",
    "${Kalip.cahdiMustagrak}${Veri.hareke[6]}",
    "${Kalip.nefiHal}${Veri.hareke[2]}",
    "${Kalip.nefiIstikbal}${Veri.hareke[2]}",
    "${Kalip.tekitNefiIstikbal}${Veri.hareke[0]}",
    "${Kalip.emriGaib}${Veri.hareke[6]}",
    "${Kalip.nehiGaib}${Veri.hareke[6]}",
    Kalip.emriHadir,
    Kalip.nehiHadir,
    Kalip.ismiMekan,
    Kalip.ismiAlet,
    Kalip.merreMastar,
    Kalip.neviMastar,
    Kalip.ismiTasgir,
    Kalip.ismiMensub,
    Kalip.mubalagaIsmiFail,
    Kalip.ismiTafdil,
    Kalip.taaccub1,
    Kalip.taaccub2,
  ];
}
